export const product = [
    {
        id: 1,
        name: "ComfortBlend men's T-shirt",
        price: 50,
        productOwner: "FashionHub",
        description: "Experience ultimate comfort with our soft and breathable ComfortBlend Women's T-shirt.",
        quantity: 1,
        src: require("../assets/products/tshirt-2.jpg"),
        subtitle: "Available in various colors and sizes",
        category: "Clothing",
        rating: 3
    },
    {
        id: 2,
        name: "ComfortBlend Women's T-shirt",
        price: 20,
        productOwner: "FashionHub",
        description: "Experience ultimate comfort with our soft and breathable ComfortBlend Women's T-shirt.",
        quantity: 1,
        src: require("../assets/products/tshirt.jpg"),
        subtitle: "Available in various colors and sizes",
        category: "Clothing",
        rating: 4
    },
    {
        id: 3,
        name: "Casual Men's Button-Up Shirt",
        price: 30,
        productOwner: "StyleBoutique",
        description: "Elevate your casual style with our comfortable and stylish men's button-up shirt.",
        quantity: 1,
        src: require("../assets/products/shirt.jpg"),
        subtitle: "Perfect for any occasion",
        category: "Clothing",
        rating: 4
    },
    {
        id: 4,
        name: "Elegant Women's Handbag",
        price: 150,
        productOwner: "ChicStyle",
        description: "Add a touch of elegance to your look with our stylish women's handbag.",
        quantity: 1,
        src: require("../assets/products/bag.jpg"),
        subtitle: "Spacious and fashionable",
        category: "Bag",
        rating: 5
    },
    {
        id: 5,
        name: "Interactive Educational Robot Toy",
        price: 380,
        productOwner: "PlaySmart",
        description: "Make learning fun with our interactive educational robot toy for kids.",
        quantity: 1,
        src: require("../assets/products/robort.jpg"),
        subtitle: "Teaches basic programming concepts",
        category: "Toys",
        rating: 5
    },
    {
        id: 6,
        name: "Steel Cookware Set",
        price: 120,
        productOwner: "KitchenMasters",
        description: "Upgrade your kitchen with our premium stainless steel cookware set.",
        quantity: 1,
        src: require("../assets/products/set.jpg"),
        subtitle: "Durable and easy to clean",
        category: "Kitchen",
        rating: 4
    },
    {
        id: 7,
        name: "ComfortBlend Women's T-shirt",
        price: 85,
        productOwner: "FashionHub",
        description: "Experience ultimate comfort with our soft and breathable ComfortBlend Women's T-shirt.",
        quantity: 1,
        src: require("../assets/products/womenTshirt.jpg"),
        subtitle: "Available in various colors and sizes",
        category: "Clothing",
        rating: 3
    },
    {
        id: 8,
        name: "Casual Men's Button-Up Shirt",
        price: 30,
        productOwner: "StyleBoutique",
        description: "Elevate your casual style with our comfortable and stylish men's button-up shirt.",
        quantity: 1,
        src: require("../assets/products/menShirt.jpg"),
        subtitle: "Perfect for any occasion",
        category: "Clothing",
        rating: 3
    },
    {
        id: 9,
        name: "Elegant Women's Handbag",
        price: 50,
        productOwner: "ChicStyle",
        description: "Add a touch of elegance to your look with our stylish women's handbag.",
        quantity: 1,
        src: require("../assets/products/bag1.jpg"),
        subtitle: "Spacious and fashionable",
        category: "Bag",
        rating: 3
    },
    {
        id: 10,
        name: "Interactive Educational Robot Toy",
        price: 400,
        productOwner: "PlaySmart",
        description: "Make learning fun with our interactive educational robot toy for kids.",
        quantity: 1,
        src: require("../assets/products/robort1.jpg"),
        subtitle: "Teaches basic programming concepts",
        category: "Toys",
        rating: 4
    },
    {
        id: 11,
        name: "Premium Stainless Steel Cookware Set",
        price: 200,
        productOwner: "KitchenMasters",
        description: "Upgrade your kitchen with our premium stainless steel cookware set.",
        quantity: 1,
        src: require("../assets/products/set1.jpg"),
        subtitle: "Durable and easy to clean",
        category: "Kitchen",
        rating: 4
    },
    {
        id: 12,
        name: "Adidas Running Shoes",
        price: 1200,
        productOwner: "Adidas",
        description: "you're a seasoned runner or just starting, these shoes are your perfect companion for the daily run and fashionable shoes. ",
        quantity: 1,
        src: require("../assets/media/adidasShoes.jfif"),
        subtitle: "Perfect for your daily run",
        category: "Footware",
        rating: 2,
    },
    {
        id: 13,
        name: "Nike Jordan",
        price: 8000,
        productOwner: "Nike",
        description: "Iconic Jordan basketball shoes for style and performance.",
        quantity: 1,
        src: require("../assets/media/jordan.jfif"),
        subtitle: "Air Jordan Collection",
        category: "Footware",
        rating: 3
    },
    {
        id: 14,
        name: "Nike Sports Shoes",
        price: 5000,
        productOwner: "Nike",
        description: "Versatile sports shoes designed for maximum comfort and performance.",
        quantity: 1,
        src: require("../assets/media/nikeSportsShoes.webp"),
        subtitle: "Ideal for various sports activities",
        category: "Sports",
        rating: 4,
    },
    {
        id: 15,
        name: "Nike Slipper",
        price: 2000,
        productOwner: "Nike",
        description: "Casual and comfortable slipper for everyday wear.",
        quantity: 1,
        src: require("../assets/media/nikeSlipper.jfif"),
        subtitle: "Easygoing style",
        category: "Footware",
        rating: 5,
    },
    {
        id: 16,
        name: "Nike Sandal",
        price: 1000,
        productOwner: "Nike",
        description: "Light and breathable sandals for a relaxed feel.",
        quantity: 1,
        src: require("../assets/media/nikeSandal.jfif"),
        subtitle: "Summer-ready footwear",
        category: "Footware",
        rating: 2,
    },
    {
        id: 17,
        name: "Nike Sneaker",
        price: 300,
        productOwner: "Nike",
        description: "Classic sneaker style for casual outings.",
        quantity: 1,
        src: require("../assets/media/nikeSneaker.jfif"),
        subtitle: "Everyday comfort",
        category: "Footware",
        rating: 3,
    },
    {
        id: 18,
        name: "Leather Shoes",
        price: 450,
        productOwner: "Generic Brand",
        description: "Formal leather shoes for a polished look.",
        quantity: 1,
        src: require("../assets/media/formal Shoes.webp"),
        subtitle: "Elegant formal wear",
        category: "Footware",
        rating: 4,
    },
    {
        id: 19,
        name: "Black Loafer",
        price: 30,
        productOwner: "Generic Brand",
        description: "Classic black loafers for a timeless style.",
        quantity: 1,
        src: require("../assets/media/loafer.jfif"),
        subtitle: "Casual and comfortable",
        category: "Footware",
        rating: 5,
    },
    {
        id: 20,
        name: "The Great Gatsby",
        price: 15.99,
        productOwner: "F. Scott Fitzgerald",
        description: "Dive into the roaring twenties with F. Scott Fitzgerald's masterpiece, 'The Great Gatsby.' A timeless tale of love, wealth, and the American Dream.",
        quantity: 10,
        src: require("../assets/products/great_gatsby.jpg"),
        subtitle: "Vintage",
        category: "Book",
        rating: 5
    },
    {
        id: 21,
        name: "To Kill a Mockingbird",
        price: 12.49,
        productOwner: "Harper Lee",
        description: "Harper Lee's classic novel, 'To Kill a Mockingbird,' explores themes of racial injustice and moral growth in the American South during the 1930s.",
        quantity: 8,
        src: require("../assets/products/to_kill_a_mockingbird.jpg"),
        subtitle: "Harper Perennial Modern Classics",
        category: "Book",
        rating: 4
    },
    {
        id: 22,
        name: "The Hobbit",
        price: 18.75,
        productOwner: "J.R.R. Tolkien",
        description: "Embark on a magical journey with J.R.R. Tolkien's 'The Hobbit.' Join Bilbo Baggins on an epic adventure filled with dwarves, dragons, and the pursuit of treasure.",
        quantity: 1,
        src: require("../assets/products/the_hobbit.jpg"),
        subtitle: "Mariner Books",
        category: "Book",
        rating: 5
    },
    {
        id: 23,
        name: "Educated: A Memoir",
        price: 22.99,
        productOwner: "Tara Westover",
        description: "Experience the power of education and resilience in Tara Westover's memoir, 'Educated.' A compelling story of overcoming obstacles and seeking knowledge.",
        quantity: 1,
        src: require("../assets/products/educated.jpg"),
        subtitle: "Random House",
        category: "Book",
        rating: 4
    },
    {
        id: 24,
        name: "Premium Wireless Bluetooth Headphones",
        price: 69.99,
        productOwner: "TechTrends",
        description: "Immerse yourself in superior sound quality with our premium wireless Bluetooth headphones. Enjoy the freedom of wireless connectivity and a comfortable, ergonomic design for extended listening pleasure.",
        quantity: 1,
        src: require("../assets/products/headphones.jpg"),
        subtitle: "High-fidelity audio for an unparalleled listening experience",
        category: "Electronics",
        rating: 4
    },
    {
        id: 25,
        name: "Smartwatch Fitness Tracker",
        price: 129.99,
        productOwner: "TechGadgets",
        description: "Stay connected and fit with our feature-packed Smartwatch Fitness Tracker. Monitor your health, receive notifications, and track your workouts seamlessly with this stylish and functional smartwatch.",
        quantity: 1,
        src: require("../assets/products/smartwatch.webp"),
        subtitle: "Multi-functional with heart rate monitoring and GPS tracking",
        category: "Electronics",
        rating: 3
    },
    {
        id: 26,
        name: "4K Ultra HD Smart TV",
        price: 699.99,
        productOwner: "TCL Technology",
        description: "Experience the brilliance of 4K Ultra HD with our Smart TV. Enjoy vibrant colors, sharp clarity, and a world of entertainment with built-in smart features for streaming your favorite content.",
        quantity: 1,
        src: require("../assets/products/smart_tv1.webp"),
        subtitle: "Smart functionality with streaming apps and voice control",
        category: "Electronics",
        rating: 4
    },
    {
        id: 27,
        name: "Compact Wireless Mouse",
        price: 24.99,
        productOwner: "Logitech",
        description: "Enhance your computing experience with our Compact Wireless Mouse. Enjoy precision and convenience with a compact design, wireless connectivity, and responsive controls.",
        quantity: 1,
        src: require("../assets/products/wireless_mouse1.jpg"),
        subtitle: "Ergonomic design for comfortable use on the go",
        category: "Electronics",
        rating: 4
    },
    {
        id: 28,
        name: "High-Performance Running Shoes",
        price: 75,
        productOwner: "SportsGearPro",
        description: "Enhance your running experience with our high-performance running shoes. Designed for comfort and durability, these shoes are your perfect companion on the track.",
        quantity: 1,
        src: require("../assets/products/running-shoes.jpg"),
        subtitle: "Available in various sizes and colors",
        category: "Sports",
        rating: 4
    },
    {
        id: 29,
        name: "Smart Fitness Tracker",
        price: 50,
        productOwner: "TechFit",
        description: "Stay on top of your fitness goals with our Smart Fitness Tracker. Monitor your steps, heart rate, and more with this sleek and intuitive device.",
        quantity: 1,
        src: require("../assets/products/fitness-tracker.png"),
        subtitle: "Water-resistant and compatible with smartphones",
        category: "Sports",
        rating: 4
    },
    {
        id: 30,
        name: "Insulated Sports Water Bottle",
        price: 15,
        productOwner: "HydraGear",
        description: "Stay hydrated on the go with our Insulated Sports Water Bottle. Keeps your drinks cold or hot for extended periods, making it ideal for workouts and outdoor activities.",
        quantity: 1,
        src: require("../assets/products/water-bottle1.jpg"),
        subtitle: "BPA-free and easy to carry",
        category: "Sports",
        rating: 4
    },
    {
        id: 31,
        name: "Compression Leggings for Men",
        price: 30,
        productOwner: "FitFlex",
        description: "Maximize your performance with our Compression Leggings. Engineered for support and flexibility, these leggings are perfect for intense workouts and sports activities.",
        quantity: 1,
        src: require("../assets/products/compression-leggings2.jpg"),
        subtitle: "Moisture-wicking and breathable fabric",
        category: "Sports",
        rating: 4
    },
    {
        id: 32,
        name: "Premium Leather-bound Journal",
        price: 25,
        productOwner: "WriteWell",
        description: "Capture your thoughts in style with our premium leather-bound journal. Features high-quality paper for a smooth writing experience.",
        quantity: 1,
        src: require("../assets/products/journal.jpg"),
        subtitle: "Perfect for journaling and note-taking",
        category: "Stationery",
        rating: 5
    },
    {
        id: 33,
        name: "Elegant Fountain Pen Set",
        price: 35,
        productOwner: "InkCraft",
        description: "Add a touch of sophistication to your writing experience with our elegant fountain pen set. Comes in a beautiful gift box.",
        quantity: 1,
        src: require("../assets/products/fountain_pen.jpg"),
        subtitle: "Refillable and durable",
        category: "Stationery",
        rating: 4
    },
    {
        id: 34,
        name: "Assorted Sticky Note Set",
        price: 12,
        productOwner: "NoteMasters",
        description: "Stay organized with our vibrant assorted sticky note set. Perfect for quick reminders and note-taking.",
        quantity: 1,
        src: require("../assets/products/sticky_notes.jpg"),
        subtitle: "Variety of shapes and sizes",
        category: "Stationery",
        rating: 4
    },
    {
        id: 35,
        name: "Designer Desk Organizer",
        price: 28,
        productOwner: "DeskCrafters",
        description: "Declutter your workspace with our designer desk organizer. Stylish and functional, it keeps your stationery essentials within reach.",
        quantity: 1,
        src: require("../assets/products/desk_organizer.webp"),
        subtitle: "Multiple compartments for efficient storage",
        category: "Stationery",
        rating: 5
    },
    {
        id: 36,
        name: "Professional Hammer",
        price: 49.99,
        productOwner: "ToolsMaster",
        description: "Enhance your toolbox with our high-quality Professional Hammer. Designed for durability and precision, these hammers are essential for various tasks.",
        quantity: 1,
        src: require("../assets/products/hammer_set1.jpg"),
        subtitle: "Includes different hammer types for versatile use",
        category: "Tools",
        rating: 4
    },
    {
        id: 37,
        name: "Cordless Drill Kit",
        price: 89.99,
        productOwner: "ToolTech",
        description: "Empower your DIY projects with our Cordless Drill Kit. Versatile and powerful, it's perfect for a range of drilling and fastening applications.",
        quantity: 1,
        src: require("../assets/products/cordless_drill1.jpg"),
        subtitle: "Includes rechargeable battery and various drill bits",
        category: "Tools",
        rating: 5
    },
    {
        id: 38,
        name: "Precision Screwdriver Set",
        price: 29.99,
        productOwner: "FixItRight",
        description: "Achieve precision in every screwing task with our Precision Screwdriver Set. Compact and versatile, it's a must-have for any toolkit.",
        quantity: 1,
        src: require("../assets/products/screwdriver_set1.jpg"),
        subtitle: "Includes a variety of screwdriver tips for different applications",
        category: "Tools",
        rating: 4
    },
    {
        id: 39,
        name: "Heavy-Duty Power Saw",
        price: 149.99,
        productOwner: "CuttingEdgeTools",
        description: "Cut through challenges effortlessly with our Heavy-Duty Power Saw. Engineered for precision and power, it's the go-to tool for woodworking and more.",
        quantity: 1,
        src: require("../assets/products/power_saw.jpg"),
        subtitle: "Equipped with a powerful motor and adjustable cutting angles",
        category: "Tools",
        rating: 4
    },
    {
        id: 40,
        name: "Contemporary Leather Sofa",
        price: 699,
        productOwner: "HomeElegance",
        description: "Upgrade your living room with the sleek and luxurious Contemporary Leather Sofa. Crafted for both style and comfort, this sofa adds a touch of modern elegance to your home.",
        quantity: 1,
        src: require("../assets/products/leather_sofa.avif"),
        subtitle: "Available in black, brown, and white",
        category: "Furniture",
        rating: 5
    },
    {
        id: 41,
        name: "Rustic Wooden Coffee Table",
        price: 249,
        productOwner: "WoodCrafters",
        description: "Bring warmth and charm to your living space with our Rustic Wooden Coffee Table. Handcrafted with care, this table combines functionality with rustic aesthetics for a cozy atmosphere.",
        quantity: 1,
        src: require("../assets/products/wooden_coffee_table.jpg"),
        subtitle: "Solid wood construction for durability",
        category: "Furniture",
        rating: 4
    },
    {
        id: 42,
        name: "Modern Glass Dining Set",
        price: 899,
        productOwner: "DineInStyle",
        description: "Elevate your dining experience with our Modern Glass Dining Set. The sleek design and quality craftsmanship make it a perfect addition to contemporary dining spaces.",
        quantity: 1,
        src: require("../assets/products/glass_dining_set.jpg"),
        subtitle: "Includes table and four chairs",
        category: "Furniture",
        rating: 5
    },
    {
        id: 43,
        name: "Adjustable Office Chair",
        price: 149,
        productOwner: "ErgoComfort",
        description: "Enhance your workspace with the Adjustable Office Chair. Ergonomically designed for maximum comfort and support, this chair ensures a productive and comfortable work environment.",
        quantity: 1,
        src: require("../assets/products/office_chair.png"),
        subtitle: "Customizable height and tilt",
        category: "Furniture",
        rating: 4
    },
    {
        id: 44,
        name: "Eternal Sparkle Diamond Necklace",
        price: 500,
        productOwner: "LuxuryJewels",
        description: "Adorn yourself with timeless elegance. Our Eternal Sparkle Diamond Necklace is crafted with precision and features exquisite diamonds that reflect everlasting beauty.",
        quantity: 1,
        src: require("../assets/products/diamond_necklace.jpg"),
        subtitle: "18K White Gold | Certified Diamonds",
        category: "Jewelry",
        rating: 5
    },
    {
        id: 45,
        name: "Gemstone Harmony Stud Earrings",
        price: 120,
        productOwner: "GlamourGems",
        description: "Add a touch of color to your style with our Gemstone Harmony Stud Earrings Set. Each pair is crafted with vibrant gemstones that exude sophistication.",
        quantity: 1,
        src: require("../assets/products/gemstone_earrings_set.webp"),
        subtitle: "Sterling Silver | Variety of Gemstones",
        category: "Jewelry",
        rating: 4
    },
    {
        id: 46,
        name: "Timeless Pearl Elegance Bracelet",
        price: 180,
        productOwner: "PearlEssence",
        description: "Embrace classic sophistication with our Timeless Pearl Elegance Bracelet. Each pearl is carefully selected to create a piece that complements any ensemble.",
        quantity: 1,
        src: require("../assets/products/pearl_bracelet.webp"),
        subtitle: "Genuine Freshwater Pearls | 14K Gold Clasp",
        category: "Jewelry",
        rating: 5
    },
    {
        id: 47,
        name: "Royal Sapphire Vintage Ring",
        price: 350,
        productOwner: "RoyalGems",
        description: "Channel your inner royalty with our Royal Sapphire Vintage Ring. This exquisite piece combines vintage charm with the regal allure of sapphires.",
        quantity: 1,
        src: require("../assets/products/sapphire_ring.webp"),
        subtitle: "14K White Gold | Natural Blue Sapphires",
        category: "Jewelry",
        rating: 5
    }
]